docs: fix: npx react-native init が失敗する問題に暫定対処
v0.76.0以降だと以下のエラーで失敗する

$ npx react-native init --npm --template https://github.com/ws-4020/rn-spoiler#v2024.10.0 dummy

⚠️ The `init` command is deprecated.
The behavior will be changed on 2024/12/31 (39 days).

- Switch to npx @react-native-community/cli init for the identical behavior.
- Refer to the documentation for information about alternative tools: https://reactnative.dev/docs/getting-started

Running: npx @react-native-community/cli init

node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: spawn npx ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn npx',
  path: 'npx',
  spawnargs: [
    '@react-native-community/cli@latest',
    'init',
    '--npm',
    '--template',
    'https://github.com/ws-4020/rn-spoiler#v2024.10.0',
    'dummy'
  ]
}

Node.js v20.17.0